// front/docvisit/src/components/register/signin.jsx
import { useState } from "react";
import axiosInstance from "../../axios/axios";
const SignIn = () => {
  const [user, setUser] = useState({
    username: "",
    password: "",
    password2: "",
  });
  const [sending, setSendeing] = useState(false);
  const [errors, setErrors] = useState("");
  const handelChange = (e) => {
    const input = e.currentTarget;
    const newUser = { ...user };
    newUser[input.name] = input.value;
    setUser(newUser);
  };

  const handelSubmit = async (e) => {
    e.preventDefault();
    try {
      setSendeing(true);
      const response = await axiosInstance.post("signin/", user);
      const token = await axiosInstance.post("api/token/", user);
      localStorage.setItem("token", token.data.access);
      console.log(response);
      setSendeing(false);
      window.location = "/";
    } catch (error) {
      setErrors("پسوردها یکسان نمیباشد");
      console.log(error);
      setSendeing(false);
    }
  };
  return (
    <>
      <form
        onSubmit={handelSubmit}
        className="container"
      >
        <div className="m-3">
          <label className="mb-4" htmlFor="username">
            شماره تلفن
          </label>
          <input
            id="username"
            className="form-control w-50"
            type="tel"
            value={user.username}
            name="username"
            onChange={handelChange}
          />
        </div>
        <div className="m-3">
          <label className="mb-4" htmlFor="password">
            رمز
          </label>
          <input
            id="password"
            className="form-control w-50"
            type="password"
            value={user.password}
            name="password"
            onChange={handelChange}
          />
        </div>
        <div className="m-3">
          <label className="mb-4" htmlFor="password2">
            تایید رمز
          </label>
          <input
            id="password2"
            className="form-control w-50"
            type="password"
            value={user.password2}
            name="password2"
            onChange={handelChange}
          />
        </div>
        <div className="w-50 text-center">
          <button disabled={sending} className="btn btn-lg btn-info">
            {sending ? "درحال ارسال ..." : "ارسال"}
          </button>
        </div>
      </form>
      {errors && <div className="alert alert-danger my-2">{errors}</div>}
    </>
  );
};

export default SignIn;

// front-angular/docAngular/src/app/sign-in/sign-in.component.ts
import { Component } from '@angular/core';
import { NgForm, NgModel } from '@angular/forms';
import axiosInstance from '../axios/axiosinstance';
import { Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { NgIf } from '@angular/common';

@Component({
  selector: 'app-sign-in',
  standalone: true,
  imports: [FormsModule, NgIf],
  templateUrl: './sign-in.component.html',
  styleUrls: ['./sign-in.component.css'],
})
export class SignInComponent {
  sending: boolean = false;
  isValidPass: boolean = true; // Initialized as true to hide the error initially

  constructor(private router: Router) {}

  async onSubmit(f: NgForm) {
    if (!this.isValidPass) return; // Prevent submission if passwords don't match

    this.sending = true;
    try {
      const response = await axiosInstance.post('signin/', f.value);
      const token = await axiosInstance.post('api/token/', f.value);
      localStorage.setItem('token', token.data.access);
      this.sending = false;
      window.location.href = '';
    } catch (error) {
      this.sending = false;
    }
  }

  passwordsMatch(password: NgModel, confirmPassword: NgModel): void {
    this.isValidPass = password.value === confirmPassword.value;
  }
}

<form class="container my-5" (ngSubmit)="onSubmit(f)" #f="ngForm">
    <!-- Username Field -->
    <div class="form-group my-3 w-50">
      <label for="username">نام کاربری:</label>
      <input
        type="text"
        name="username"
        id="username"
        ngModel
        #username="ngModel"
        class="form-control my-2"
        required
        minlength="8"
      />
      <div *ngIf="username.invalid && username.touched">
        <div *ngIf="username.errors?.['required']" class="alert alert-danger my-1">
          نام کاربری خود را وارد کنید
        </div>
        <div *ngIf="username.errors?.['minlength']" class="alert alert-danger my-1">
          نام کاربری حداقل باید هشت کاراکتر داشته باشد
        </div>
      </div>
    </div>
  
    <!-- Password Field -->
    <div class="form-group my-3 w-50">
      <label for="password">رمز عبور:</label>
      <input
        type="password"
        name="password"
        id="password"
        ngModel
        #password="ngModel"
        class="form-control my-2"
        required
        minlength="10"
        (input)="passwordsMatch(password, confirmPassword)"
      />
      <div *ngIf="password.invalid && password.touched">
        <div *ngIf="password.errors?.['required']" class="alert alert-danger my-1">
          رمز عبور خود را وارد کنید
        </div>
        <div *ngIf="password.errors?.['minlength']" class="alert alert-danger my-1">
          رمز عبور حداقل باید ده کاراکتر داشته باشد
        </div>
      </div>
    </div>
  
    <!-- Confirm Password Field -->
    <div class="form-group my-3 w-50">
      <label for="confirm_password">تکرار رمز عبور:</label>
      <input
        type="password"
        name="password2"
        id="confirm_password"
        ngModel
        #confirmPassword="ngModel"
        class="form-control my-2"
        required
        (input)="passwordsMatch(password, confirmPassword)"
      />
      <div *ngIf="confirmPassword.invalid && confirmPassword.touched">
        <div *ngIf="confirmPassword.errors?.['required']" class="alert alert-danger my-1">
          تکرار رمز عبور خود را وارد کنید
        </div>
      </div>
      <div *ngIf="!isValidPass && confirmPassword.touched" class="alert alert-danger my-1">
        پسوردها با یکدیگر تطابق ندارند
      </div>
    </div>
      <button
      [disabled]="f.invalid || sending || !isValidPass"
      type="submit"
      class="btn btn-lg btn-primary my-3"
    >
      {{ sending ? "در حال ارسال ..." : "ارسال" }}
    </button>
  </form>
