// front-angular/docAngular/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import axiosInstance from '../axios/axiosinstance';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
})
export class LoginComponent {
  constructor(private router: Router) {}
  sending: boolean = false;

  async onSubmit(f: any) {
    this.sending = true;
    try {
      const response = await axiosInstance.post('login/', f.value);
      const token = await axiosInstance.post('api/token/', f.value);
      localStorage.setItem('token', token.data.access);
      this.sending = false;
      window.location.href = ''
    } catch (error) {
      this.sending = false;
    }
  }
}

<form class="container my-5" (ngSubmit)="onSubmit(f)" #f="ngForm">
  <div class="form-group my-3 w-50">
    <label for="username">نام کاربری:</label>
    <input
      type="text"
      name="username"
      id="username"
      ngModel
      #username="ngModel"
      type="text"
      class="form-control my-2"
      id="exampleInputEmail1"
      aria-describedby="emailHelp"
      required
    />
    @if (username.invalid && username.touched) { @if
    (username.hasError('required')) {
    <div class="alert alert-danger my-1">نام کاربری خود را وارد کنید</div>
    } }
  </div>
  <div class="form-group my-3 w-50">
    <label for="password">رمز عبور:</label>
    <input
      type="password"
      name="password"
      class="form-control my-2"
      id="password"
      ngModel
      #password="ngModel"
      required
    />
    @if (password.invalid && password.touched) { @if
    (password.hasError('required')) {
    <div class="alert alert-danger my-1">رمز عبور خود را وارد کنید</div>
    } }
  </div>
  <button [disabled]="f.invalid || sending" type="submit" class="btn btn-lg btn-primary my-3">{{sending ? "در حال ارسال ..." : "ارسال"}}</button>
</form>

// front/docvisit/src/components/register/login.jsx
import { useState } from "react";
import axiosInstance from "../../axios/axios";
const LogIn = () => {
  const [user, setUser] = useState({
    username: "",
    password: "",
  });
  const [sending, setSendeing] = useState(false);
  const [errors, setErrors] = useState("");
  const handelChange = (e) => {
    const input = e.currentTarget;
    const newUser = { ...user };
    newUser[input.name] = input.value;
    setUser(newUser);
  };

  const handelSubmit = async (e) => {
    e.preventDefault();
    try {
      setSendeing(true);
      const response = await axiosInstance.post("login/", user);
      const token = await axiosInstance.post("api/token/", user);
      localStorage.setItem("token", token.data.access);
      console.log(response);
      setSendeing(false);
      window.location = "/";
    } catch (error) {
      setErrors("نام کاربری موجود نمی باشد یا رمز نادرست است");
      console.log(error);
      setSendeing(false);
    }
  };
  return (
    <>
      <form
        onSubmit={handelSubmit}
        className="container"
      >
        <div className="m-3">
          <label className="mb-4" htmlFor="username">
            شماره تلفن
          </label>
          <input
            id="username"
            className="form-control w-50"
            type="tel"
            value={user.username}
            name="username"
            onChange={handelChange}
          />
        </div>
        <div className="m-3">
          <label className="mb-4" htmlFor="password">
            رمز
          </label>
          <input
            id="password"
            className="form-control w-50"
            type="password"
            value={user.password}
            name="password"
            onChange={handelChange}
          />
        </div>
        <div className="w-50 text-center">
          <button disabled={sending} className="btn btn-lg btn-info">
            {sending ? "در حال ارسال..." : "ارسال"}
          </button>
        </div>
      </form>
      {errors && <div className="alert alert-danger my-2">{errors}</div>}
    </>
  );
};

export default LogIn;
