// front-angular/docAngular/src/app/admin/admin.component.ts
import { Component, OnInit } from '@angular/core';
import axiosInstance from '../axios/axiosinstance';
import { format } from 'date-fns';
import Converter from 'persian-date-converter/index';
import { FormsModule, NgForm } from '@angular/forms';
import { NgModule } from '@angular/core';
import { NgPersianDatepickerModule } from 'ng-persian-datepicker';
import { ReactiveFormsModule, FormControl } from '@angular/forms';
import { NgxMaterialTimepickerModule } from 'ngx-material-timepicker';
import { NgxMatTimepickerModule } from 'ngx-mat-timepicker';
import { date } from 'yup';
import { NgIf } from '@angular/common';

@Component({
  selector: 'app-admin',
  standalone: true,
  imports: [
    FormsModule,
    NgPersianDatepickerModule,
    ReactiveFormsModule,
    NgxMatTimepickerModule,
    NgIf,
    FormsModule,
  ],
  templateUrl: './admin.component.html',
  styleUrls: ['./admin.component.css'],
})
export class AdminComponent implements OnInit {
  patients: any;
  user: any;
  userId: any;
  phisicalVisit: any;
  phisicalSendeing: boolean = false;
  sendeing: boolean = false;
  massage: string = '';
  dateValue = new FormControl();
  dateValuePhi = new FormControl();
  phisicalVisitDATA = {
    visit_date: null,
    visit_time: null,
  };
  async ngOnInit() {
    try {
      const response = await axiosInstance.get('allpatient/');
      const userResponse = await axiosInstance.get('user/');
      this.patients = response.data;
      this.user = userResponse.data;
      this.userId = userResponse.data.id;
    } catch (error) {
      console.log(error);
    }
  }
  _date = new Converter();
  toJalali(date: any) {
    let newDate: any = this._date.convert(date, 'fa');
    return newDate;
  }
  toMiladi(date: any) {
    let newDate: any = this._date.convert(date, 'en');
    const ISODate = format(newDate, 'yyyy-MM-dd');
    return ISODate;
  }
  async onClickPhisicalVisit(
    ID: number,
    NAME: string,
    NATIONALID: string,
    FATHERNAME: string,
    DESCRIPTION: string,
    EMAIL: string
  ) {
    let data = {
      user: this.userId,
      name: NAME,
      national_id: NATIONALID,
      father_name: FATHERNAME,
      description: DESCRIPTION,
      email: EMAIL,
      visit_date: this.toMiladi(this.phisicalVisitDATA.visit_date),
      visit_time: this.phisicalVisitDATA.visit_time,
    };
    try {
      this.phisicalSendeing = true;
      const response = await axiosInstance.put(`patient/${ID}/`,data);
      this.phisicalSendeing = false;
    } catch (error) {
      this.phisicalSendeing = false;
    }
  }
  async onSunmitAutoVisit(f: NgForm) {
    let autoVisit = {
      date: this.toMiladi(this.dateValue.value),
      ...f.value,
    };
    try {
      this.sendeing = true;
      const response = await axiosInstance.post('autovisit/', autoVisit);
      console.log(response.data);
      const response2 = await axiosInstance.get('allpatient/');
      this.patients = response2.data;
      this.sendeing = false;
      this.massage = 'نوبت ها با موفقیت ثبت شدند';
    } catch (error) {
      console.log(error);
      this.massage = 'لطفا مقادیر صحیح وار نمایید';
      this.sendeing = false;
    }
  }
  onSearch(e: Event) {
    const input = e.target as HTMLInputElement;

    const ids = document.querySelectorAll('.na_id');
    ids.forEach((f: any) => {
      const parent = f.closest('.admin-t_body');
      if (f.innerText.includes(input.value)) {
        parent.style.display = 'block';
      } else {
        parent.style.display = 'none';
      }
    });
  }
}

<form (ngSubmit)="onSunmitAutoVisit(f)" #f="ngForm" class="w-100 autoVisitSec">
  <ng-persian-datepicker>
    <label class="my-1" for="pickdate">تاریخ:</label>
    <input
      placeholder="تاریخ"
      id="pickdate"
      class="form-control"
      type="text"
      [formControl]="dateValue"
      required
    />
  </ng-persian-datepicker>
  <div>
    <label class="my-1" for="from_time">از ساعت:</label>
    <input
      id="from_time"
      class="form-control"
      type="time"
      name="from_time"
      ngModel
      #fromTime="ngModel"
      placeholder="از ساعت"
      step="2"
      required
    />
  </div>
  <div>
    <label class="my-1" for="to_time">تا ساعت:</label>
    <input
      id="to_time"
      class="form-control"
      type="time"
      name="to_time"
      ngModel
      #toTime="ngModel"
      placeholder="تا ساعت"
      step="2"
      required
    />
  </div>
  <div>
    <label class="my-1" for="for_time">به مدت:</label>
    <input
      id="for_time"
      class="form-control"
      type="time"
      name="for_time"
      ngModel
      #forTime="ngModel"
      placeholder="به مدت"
      step="2"
      required
    />
  </div>
  <div class="text-center">
    <label class="my-4 d-block"></label>
    <button [disabled]="sendeing || f.invalid" class="btn btn-primary">
      ثبت
    </button>
  </div>
  <div *ngIf="massage" class="w-100 my-3 text-center text-dark">
    {{ massage }}
  </div>
</form>

<section class="my-5 phisicalVisitSec">
  <div class="text-center w-100">
    <input
      class="form-control w-25 m-4"
      type="search"
      placeholder="جستو جو"
      (input)="onSearch($event)"
    />
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>نام بیمار</th>
        <th>کد ملی بیمار</th>
        <th>نام پدر بیمار</th>
        <th>تاریخ مراجعه</th>
        <th>زمان مراجعه</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @for (patient of patients; track patient) {
      <tr class="admin-t_body">
        <td scope="row">{{ patient.name }}</td>
        <td class="na_id">{{ patient.national_id }}</td>
        <td>{{ patient.father_name }}</td>
        <td>
          <span>
            <ng-persian-datepicker>
              <input
                placeholder="تاریخ"
                id="pickdate"
                class="form-control"
                type="text"
                [formControl]="dateValuePhi"
                required
                [(ngModel)]="phisicalVisitDATA.visit_date"
              />
            </ng-persian-datepicker>
          </span>
          <span class="my-1">{{
            patient.visit_date ? toJalali(patient.visit_date) : "_____"
          }}</span>
        </td>
        <td>
          <span>
            <input
              id="time"
              class="form-control"
              type="time"
              name="visit_time"
              ngModel
              #forTime="ngModel"
              placeholder="به مدت"
              step="2"
              required
              [(ngModel)]="phisicalVisitDATA.visit_time"
            />
          </span>
          <span class="my-1">
            {{ patient.visit_time ?? "_____" }}
          </span>
        </td>
        <td>
          <button
            (click)="
              onClickPhisicalVisit(
                patient.id,
                patient.name,
                patient.national_id,
                patient.father_name,
                patient.description,
                patient.email
              )
            "
            class="btn btn-primary"
            [disabled]="phisicalSendeing"
          >
            ثبت
          </button>
        </td>
      </tr>
      }
    </tbody>
  </table>
</section>

// front/docvisit/src/components/admin.jsx
import axiosInstance from "../axios/axios";
import { useState, useEffect } from "react";
import DatePicker from "react-multi-date-picker";
import jalaali from "jalaali-js";
import { format, set } from "date-fns";
import persian from "react-date-object/calendars/persian";
import persian_fa from "react-date-object/locales/persian_fa";
import TimePicker from "react-multi-date-picker/plugins/time_picker";
import "../components/static/css/admin.css";
const Admin = () => {
  const [patients, setPatients] = useState([]);
  const [user, setUser] = useState({});
  const [errors, setErrors] = useState("");
  const [massage, setMassage] = useState("");
  const [sending, setSendeing] = useState(false);
  const [phisicalSending, setPhisicalSendeing] = useState(false);
  const [autoVisit, setAutoVisit] = useState({
    date: null,
    from_time: null,
    to_time: null,
    for_time: null,
  });
  const [phisicalVisit, setPhisicalVisit] = useState({
    user: "",
    name: "",
    national_id: "",
    father_name: "",
    description: "",
    email: "",
    visit_date: null,
    visit_time: null,
  });
  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await axiosInstance.get("allpatient/");
        const userResponse = await axiosInstance.get("user/");
        setPatients(response.data);
        setUser(userResponse.data);
        setPhisicalVisit((pre) => ({ ...pre, user: userResponse.data.id }));
      } catch (error) {
        setErrors("مشکلی پیش آمده لطفا مجددا امتحان کنید");
      }
    };
    fetchData();
  }, []);
  const handelSubmit = async (e) => {
    e.preventDefault();
    try {
      setSendeing(true);
      const response = await axiosInstance.post("autovisit/", autoVisit);
      const response2 = await axiosInstance.get("allpatient/");
      setPatients(response2.data);
      setSendeing(false);
      setMassage("نوبت ها با موفقیت ثبت شدند");
    } catch (error) {
      setErrors("پسوردها یکسان نمیباشد");
      setSendeing(false);
      setMassage("");
    }
  };
  const convertToGregorian = (jy, jm, jd) => {
    const gregorianDate = jalaali.toGregorian(jy, jm, jd);
    const finalDate = new Date(
      gregorianDate.gy,
      gregorianDate.gm - 1,
      gregorianDate.gd
    );
    const ISODate = format(finalDate, "yyyy-MM-dd");
    return ISODate;
  };
  const convertToJalaali = (gregorianDate) => {
    const jalaaliDate = jalaali.toJalaali(new Date(gregorianDate));
    return `${jalaaliDate.jy}/${jalaaliDate.jm}/${jalaaliDate.jd}`;
  };
  const handelClick = async (ID) => {
    try {
      setPhisicalSendeing(true);
      const response = await axiosInstance.put(`patient/${ID}/`, phisicalVisit);
      setPhisicalSendeing(false);
    } catch (error) {
      setErrors("پسوردها یکسان نمیباشد");
      setPhisicalSendeing(false);
    }
  };
  const handleSearch = (e) => {
    const input = e.currentTarget;

    const ids = document.querySelectorAll(".na_id");
    ids.forEach((f) => {
      const parent = f.closest(".admin-t_body");
      if (f.innerText.includes(input.value)) {
        parent.style.display = "flex";
      } else {
        parent.style.display = "none";
      }
    });
  };

  return (
    <div className="container-fluied">
      <form onSubmit={handelSubmit} className="auto_visit">
        <div className="lab_inp">
          <label htmlFor="date">در تاریخ:</label>
          <DatePicker
            id="date"
            calendar={persian}
            locale={persian_fa}
            onChange={(value) =>
              setAutoVisit((prevPatient) => ({
                ...prevPatient,
                date: convertToGregorian(value.year, value.month, value.day),
              }))
            }
          />
        </div>
        <div className="lab_inp">
          <label htmlFor="from_time">از ساعت:</label>
          <DatePicker
            disableDayPicker
            format="HH:mm:ss"
            plugins={[<TimePicker />]}
            onChange={(value) =>
              setAutoVisit((prevPatient) => ({
                ...prevPatient,
                from_time: `${value.hour}:${value.minute}:${value.second}`,
              }))
            }
          />
        </div>
        <div className="lab_inp">
          <label htmlFor="to_time">تا ساعت:</label>
          <DatePicker
            disableDayPicker
            format="HH:mm:ss"
            plugins={[<TimePicker />]}
            onChange={(value) =>
              setAutoVisit((prevPatient) => ({
                ...prevPatient,
                to_time: `${value.hour}:${value.minute}:${value.second}`,
              }))
            }
          />
        </div>
        <div className="lab_inp">
          <label htmlFor="for_time">به مدت:</label>
          <DatePicker
            disableDayPicker
            format="HH:mm:ss"
            plugins={[<TimePicker />]}
            onChange={(value) =>
              setAutoVisit((prevPatient) => ({
                ...prevPatient,
                for_time: `${value.hour}:${value.minute}:${value.second}`,
              }))
            }
          />
        </div>
        <div className="lab_inp">
          <button disabled={sending} className="btn btn-primary">
            {sending ? "در حال ثبت ..." : "ثبت"}
          </button>
        </div>
      </form>
      <div className="m-3 text-center">
        <input
          placeholder="جستوجو"
          className="form-control w-50"
          type="search"
          onChange={handleSearch}
        />
      </div>
      <section class="admin-dv-lg ">
        <div className="t_head">
          <div className="admin-t-th">نام بیمار</div>
          <div className="admin-t-th">کد ملی بیمار</div>
          <div className="admin-t-th">نام پدر بیمار</div>
          <div className="admin-t-th">تاریخ مراجعه</div>
          <div className="admin-t-th">ساعت مراجعه</div>
          <div className="admin-t-th"></div>
        </div>

        {patients.map((m, i) => (
          <div className="admin-t_body" key={i}>
            <div className="admin-t_td">{m.name}</div>
            <div className="admin-t_td na_id">{m.national_id}</div>
            <div className="admin-t_td">{m.father_name}</div>
            <div className="admin-t_td">
              <DatePicker
                placeholder={m.visit_date && convertToJalaali(m.visit_date)}
                id="date"
                calendar={persian}
                locale={persian_fa}
                onChange={(value) =>
                  setPhisicalVisit((prevPatient) => ({
                    ...prevPatient,
                    visit_date: convertToGregorian(
                      value.year,
                      value.month,
                      value.day
                    ),
                    name: m.name,
                    national_id: m.national_id,
                    father_name: m.father_name,
                  }))
                }
              />
            </div>
            <div className="admin-t_td">
              <DatePicker
                placeholder={m.visit_time}
                disableDayPicker
                format="HH:mm:ss"
                plugins={[<TimePicker />]}
                onChange={(value) =>
                  setPhisicalVisit((prevPatient) => ({
                    ...prevPatient,
                    visit_time: `${value.hour}:${value.minute}:${value.second}`,
                    name: m.name,
                    national_id: m.national_id,
                    father_name: m.father_name,
                  }))
                }
              />
            </div>
            <div className="admin-t_td">
              <button
                disabled={phisicalSending}
                onClick={() => handelClick(m.id)}
                className="btn btn-info"
              >
                ثبت
              </button>
            </div>
          </div>
        ))}
      </section>
    </div>
  );
};

export default Admin;
